### ISSUE TITLE
PHP 5.3 support

### ISSUE THREAD

**Issue by rubenvincenten** [bruno-rodrigues/clean-inactive-images#1]
Can the php 5.4 array syntax be converted to the pre 5.4 syntax? that way older servers can use this plugin.

**Comment by bruno-rodrigues** [comment]
Hi ruben, 

Can you provide a PR with this feature?
I am a bit overwhelmed right now 😄

**Comment by stephenorr** [comment]
I've just added a PR that'll take care of this. Hope that helps.
